version: 2.1

jobs:
  build_and_check:
    docker:
      
      - image: pawelwolf/ventis2db:v3
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      
      - run:
          name: Sprawdzanie jakosci kodu (Linter)
          command: |
            make lint || true
            
workflows:
  version: 2
  weryfikacja_ventis:
    jobs:
      - build_and_check